### ISSUE TITLE
Playground: Moving rectangle demo not working

### ISSUE THREAD

**Issue by vtereshkov** [tophat2d/tophat#199]
The rectangle doesn't respond to keyboard input.

**Comment by skejeton** [comment]
Weird

**Comment by skejeton** [comment]
Which demo do you mean? The one in `samples/rect` allows you to move with the mouse.

**Comment by vtereshkov** [comment]
I mean the web playground.

**Comment by skejeton** [comment]
Ah

**Comment by skejeton** [comment]
Seems to be a Sokol issue, if you use `isPressedRepeatc` instead of `isPressedc` it will work

**Comment by skejeton** [comment]
Or rather an emscripten issue (https://github.com/emscripten-core/emscripten/pull/22201), I can't see why it would behave this way, I know that it sends key_repeat all the time, instead of just after the first time, which registers it incorrectly. I will make a temporary hot fix for this until they fix emscripten.

**Comment by vtereshkov** [comment]
Can you reproduce it with a local build? I couldn't. Everything was OK when I built it and ran on localhost.

**Comment by skejeton** [comment]
> Can you reproduce it with a local build? I couldn't. Everything was OK when I built it and ran on localhost.

Yeah, it seems to be related to some recent changes in emscripten - https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3162---070224
I specified a version that should work.

**Comment by vtereshkov** [comment]
I see. I have 3.1.56 on my laptop.

**Comment by skejeton** [comment]
Downgrading worked.
